output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGINNING OF PRE-COMMIT-TERRAFORM-DOCS HOOK -->
    {{ .Content }}
    <! -- END OF PRE-COMMIT-TERRAFORM DOCS HOOK -->

settings:
  hide-empty: true